
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 2;
  public static final int COMA = 7;
  public static final int DOSPUNTO = 6;
  public static final int TITULO = 8;
  public static final int EOF = 0;
  public static final int LLAV_C = 5;
  public static final int NUMERO = 3;
  public static final int LLAV_A = 4;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "NUMERO",
  "LLAV_A",
  "LLAV_C",
  "DOSPUNTO",
  "COMA",
  "TITULO"
  };
}

